name: leader_team_ai_bot-development

services:
  redis:
    container_name: cache_leader_team_ai_bot-dev
    image: redis
    restart: always
    ports:
      - '6661:6379'
    command: redis-server --loglevel debug

  postgres:
    container_name: postgres_leader_team_ai_bot-dev
    image: postgres
    ports:
      - '4441:5432'
    environment:
      POSTGRES_DB: "LeaderTeamAIbotDevelopment"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LeaderTeamAIbotDevelopment -p 5432"]
      interval: 30s
      timeout: 10s
      retries: 3